services:
    _defaults:
        autowire: true
        autoconfigure: true


    Becklyn\SecurityBundle\Mitigation\Breach\BreachResponseListener: ~
    Becklyn\SecurityBundle\Mitigation\Breach\HtmlNonceInjector: ~
